# Generated by Django 2.0.4 on 2018-04-23 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sides', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiceSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_sequence', to=settings.AUTH_USER_MODEL)),
                ('sequence', models.ManyToManyField(to='rollservice.Dice')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RollSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dice_sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rollservice.DiceSequence')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_sequence', to=settings.AUTH_USER_MODEL)),
                ('roll_sequence', models.ManyToManyField(to='rollservice.Roll')),
            ],
        ),
    ]
