# Generated by Django 2.0.4 on 2018-05-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rollsequence',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='dicesequence',
            old_name='name',
            new_name='seq_name',
        ),
    ]
