# Generated by Django 2.0.4 on 2018-05-03 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rollservice', '0002_auto_20180503_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicesequence',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
