# Generated by Django 2.0.4 on 2018-05-06 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rollservice', '0003_dicesequence_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicesequence',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
    ]
