# Generated by Django 2.0.4 on 2018-05-06 00:13

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    DiceSequence = apps.get_model('rollservice', 'DiceSequence')
    for row in DiceSequence.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('rollservice', '0006_auto_20180506_0007'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
